---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
...
