---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
...
