apiVersion: v1
kind: ConfigMap
metadata:
  name: config-environment
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  DB_URL: "postgres://postgres:x6cwOzI5Xt@postgresql.default:5432/simple_app"
