---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
    helm.sh/hook: post-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec: 
  template:
    spec:
      containers:
      - name: migrator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["/usr/local/bin/migrator"]
        envFrom:
          - configMapRef:
              name: config-environment
      restartPolicy: Never
  backoffLimit: 4
